modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="obliviousarchitecture" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Oblivious Architecture" #mandatory
logoFile="architecture.png" #optional
credits="Created by TsarOblivious" #optional
authors="Love, Cheese and small house plants" #optional
description='''
A Vanilla Style Mod that adds furniture, decorations and ways to craft them!
'''
[[dependencies.obliviousarchitecture]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.obliviousarchitecture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
